version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crowd_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/crowd_db
      PORT: 4000
      FRONTEND_ORIGIN: '*'
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db-data:
